{
  "todos": [
    {
      "title": "При этом в отличие от .catch() промисов, try-catch поймает не только ошибки, которые были внутри асинхронных функций, но также и ошибки, которые возникли во время обычных синхронных операций. 123",
      "completed": true,
      "id": 4
    },
    {
      "title": "новая задача",
      "completed": false,
      "id": 5
    },
    {
      "title": "ещё задача, поменял, снова поменял и ещё разок",
      "completed": false,
      "id": 6
    }
  ]
}